"""Centralized constants for the RL Escape Room game."""

# Grid constants
DEFAULT_CELL_SIZE = 48
DEFAULT_GRID_ROWS = 10
DEFAULT_GRID_COLS = 10

# Animation timing
VI_ANIMATION_DELAY_BASE = 0.3  # seconds per frame
REPLAY_DELAY_BASE = 0.4  # seconds per step at 1x speed
REPLAY_SPEEDS = [0.5, 1.0, 2.0, 4.0]
MAX_REPLAY_SPEED = 4.0
MIN_REPLAY_SPEED = 0.5

# UI constants
DEFAULT_GAMMA = 0.95
DEFAULT_TOLERANCE = 1e-6
DEFAULT_MAX_ITERATIONS = 10000
DEFAULT_EPISODES = 5000
DEFAULT_ALPHA = 0.10
DEFAULT_MAX_STEPS = 200
DEFAULT_EPSILON_START = 1.0
DEFAULT_EPSILON_MIN = 0.05
DEFAULT_EPSILON_DECAY = 0.995
DEFAULT_ROLLOUT_SEED = 42
DEFAULT_EVAL_EPISODES = 100
DEFAULT_ROLLING_WINDOW = 100

# Room 4 specific
DEFAULT_APPROX_EPISODES = 3000
DEFAULT_APPROX_ALPHA = 0.10
DEFAULT_APPROX_GAMMA = 0.99
DEFAULT_APPROX_MAX_STEPS = 750
DEFAULT_APPROX_EPSILON_START = 1.0
DEFAULT_APPROX_EPSILON_MIN = 0.02
DEFAULT_APPROX_EPSILON_DECAY = 0.997
DEFAULT_APPROX_TILINGS = 8
DEFAULT_APPROX_TILES_XY = 10
DEFAULT_APPROX_PROGRESS_SCALE = 1.0
DEFAULT_APPROX_START_MODE = "random_lower_left"
DEFAULT_APPROX_EVAL_EPISODES = 50
DEFAULT_APPROX_ROLLING_WINDOW = 100

# Comparison constants
DEFAULT_COMP_EPISODES = 2000
DEFAULT_COMP_ALPHA = 0.10
DEFAULT_COMP_GAMMA = 0.95
DEFAULT_COMP_EPSILON_DECAY = 0.995
DEFAULT_COMP_SEEDS = 5
DEFAULT_COMP_EVAL_EPISODES = 100

# Slip probability defaults
DEFAULT_SLIP_INTENDED = 0.80
DEFAULT_SLIP_LEFT = 0.10
DEFAULT_SLIP_RIGHT = 0.10

# Colors (room-specific)
ROOM1_PRIMARY = "#4fc3f7"  # Blue
ROOM2_PRIMARY = "#ef5350"  # Red
ROOM3_PRIMARY = "#ffd740"  # Gold
ROOM4_PRIMARY = "#7c4dff"  # Purple

# Grid cell size limits
MIN_CELL_SIZE = 32
MAX_CELL_SIZE = 64
DEFAULT_CELL_SIZE = 48

# Grid resolution limits for Room 4
MIN_GRID_RESOLUTION = 10
MAX_GRID_RESOLUTION = 50
DEFAULT_GRID_RESOLUTION = 30

# Achievement constants
ACHIEVEMENTS_FILE = "storage/achievements.json"

# Model storage paths
MODEL_STORAGE_BASE = "storage/models"
ROOM1_MODEL_DIR = "room1_dp"
ROOM2_MODEL_DIR = "room2_sarsa"
ROOM3_MODEL_DIR = "room3_q_learning"
ROOM4_MODEL_DIR = "room4_approximate_sarsa"
