from core.types import RoomSpec, RoomKind, RewardConfig

# Human-readable room metadata for docs/UI.  The actual environment rules live
# under environments/, while these specs describe the assignment structure.
ROOM_SPECS: dict[str, RoomSpec] = {
    "room1_dp": RoomSpec(
        room_id="room1",
        name="Ice Maze",
        kind=RoomKind.GRID_KNOWN,
        algorithm="Value Iteration (Dynamic Programming)",
        state_description="(row, column) — 100 discrete states",
        action_description="UP, RIGHT, DOWN, LEFT",
        grid_size=(10, 10),
        is_continuous=False,
        continuous_size=None,
        dt=None,
        velocity_values=None,
        rewards=RewardConfig(),
        description="Known 10x10 stochastic grid with slippery cells. Short risky route and long safe route.",
    ),
    "room2_sarsa": RoomSpec(
        room_id="room2",
        name="Laser Corridor",
        kind=RoomKind.GRID_UNKNOWN_STOCHASTIC,
        algorithm="SARSA (On-Policy TD Control)",
        state_description="(row, column) — 100 discrete states",
        action_description="UP, RIGHT, DOWN, LEFT",
        grid_size=(10, 10),
        is_continuous=False,
        continuous_size=None,
        dt=None,
        velocity_values=None,
        rewards=RewardConfig(),
        description="Unknown 10x10 stochastic grid with slippery cells and traps. SARSA learns risk-aware behaviour.",
    ),
    "room3_qlearning": RoomSpec(
        room_id="room3",
        name="Key Vault",
        kind=RoomKind.GRID_UNKNOWN,
        algorithm="Q-Learning (Off-Policy TD Control)",
        state_description="(row, column, has_key) — 200 discrete states",
        action_description="UP, RIGHT, DOWN, LEFT",
        grid_size=(10, 10),
        is_continuous=False,
        continuous_size=None,
        dt=None,
        velocity_values=None,
        rewards=RewardConfig(),
        description="Unknown 10x10 grid. Agent must collect a key before the exit becomes terminal.",
    ),
    "room4_continuous": RoomSpec(
        room_id="room4",
        name="Momentum Chamber",
        kind=RoomKind.CONTINUOUS,
        algorithm="Semi-Gradient SARSA with Tile Coding (Function Approximation)",
        state_description="(X, Y, Vx, Vy) — 4 continuous dimensions",
        action_description="UP→(0,1), RIGHT→(1,0), DOWN→(0,-1), LEFT→(-1,0), STAY→(0,0)",
        grid_size=None,
        is_continuous=True,
        continuous_size=(10.0, 10.0),
        dt=0.02,
        velocity_values=(-1, 0, 1),
        rewards=RewardConfig(step_penalty=-0.1),
        description="Continuous 10x10 metre room. Agent selects velocity directly; position updates via Euler integration.",
    ),
}
